# SQLite (development / test 環境用)
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

# PostgreSQL (Cloud9での本番用)
production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    pool: 5
    database: mysite_mtde
    username: mysite_mtde_user
    password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>
    url: <%= ENV['DATABASE_URL'] %>
